services:

  mysql:
    image: mysql
    ports:
      - "3308:3306"
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: resumebuilder

volumes:
  database: